bookstore/book/urls.py
from django.urls import path

from . import views
from .feed import LatestArrivals

app_name = "book"

urlpatterns = [
    path("", views.book_list, name="book_list"),
    path("book/<str:slug>/", views.book_detail, name="book_detail"),
    path("<int:bookid>/review/", views.post_review, name="post_review"),
    path("tag/<slug:tag_slug>/", views.book_list, name="book_list_by_tag"),
    path("search/", views.book_search, name="book_search"),
    path("category/<int:catid>/", views.category_display, name="category_display"),
    path("category/all/", views.category_display, name="all_categories"),
    path("edit_review/<int:review_id>/", views.edit_review, name="edit_review"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("feed/", LatestArrivals(), name="book_feed"),
    path("like/", views.review_like, name="like"),
]

bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("filter/", include("filter.urls", namespace="filter")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("author/", include("author.urls", namespace="author")),
    path("", include("book.urls", namespace="book")),
    path("", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path("order/<int:order_id>/", views.order_detail, name="order_detail"),
    path("order_cancel/<int:order_id>/", views.order_cancel, name="order_cancel"),
    path(
        "admin/order/<int:order_id>/",
        views.admin_order_detail,
        name="admin_order_detail",
    ),
    path(
        "admin/order/<int:order_id>/pdf/",
        views.admin_order_pdf,
        name="admin_order_pdf",
    ),
]

bookstore/payment/urls.py
from django.urls import path

from . import views
from . import webhooks

app_name = "payment"

urlpatterns = [
    path("process/", views.payment_process, name="process"),
    path("laterprocess/", views.later_payment_process, name="laterprocess"),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", webhooks.stripe_webhook, name="stripe-webhook"),
]

bookstore/user/urls.py
from django.urls import path

from . import views


app_name = "user"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
    path("shipping_address/", views.add_shipping_address, name="add_shipping_address"),
    path(
        "edit_shipping_address/<int:shipping_address_id>/",
        views.edit_shipping_address,
        name="edit_shipping_address",
    ),
    path(
        "delete_shipping_address/<int:shipping_address_id>/",
        views.delete_shipping_address,
        name="delete_shipping_address",
    ),
]

bookstore/orders/models.py
from decimal import Decimal

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

from book.models import Book
from user.models import ShippingAddress
from coupons.models import Coupon


ORDER_STATUS_CHOICES = [
    ("pending", "Pending"),
    ("processing", "Processing"),
    ("shipped", "Shipped"),
    ("canceled", "Canceled"),
]


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    shipping_address = models.ForeignKey(
        ShippingAddress, on_delete=models.CASCADE, null=False, blank=False
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    stripe_id = models.CharField(max_length=250, blank=True)
    coupon = models.ForeignKey(
        Coupon, related_name="orders", null=True, blank=True, on_delete=models.SET_NULL
    )
    discount = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    order_status = models.CharField(choices=ORDER_STATUS_CHOICES, default="pending")

    class Meta:
        ordering = ["-created"]
        indexes = [models.Index(fields=["-created"])]

    def __str__(self):
        return f"Order no {self.id}"

    def get_stripe_url(self):
        if not self.stripe_id:
            return ""
        if "_test_" in settings.STRIPE_SECRET_KEY:
            path = "/test/"  # for testing
        else:
            path = "/"  # for production
        return f"https://dashboard.stripe.com{path}payments/{self.stripe_id}"

    def get_total_cost_before_discount(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_discount(self):
        total_cost = self.get_total_cost_before_discount()
        if self.discount:
            return total_cost * (self.discount / Decimal(100))
        return Decimal(0)

    def get_total_cost(self):
        total_cost = self.get_total_cost_before_discount() - self.get_discount()
        return total_cost


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name="order_items", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

bookstore/orders/forms.py
from django import forms


class OrderCreateForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    street = forms.CharField(max_length=255)
    apartment = forms.CharField(max_length=30)
    city = forms.CharField(max_length=100)
    postal_code = forms.CharField(max_length=10)
    state = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)

bookstore/orders/views.py
import weasyprint

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string

from user.models import ShippingAddress
from cart.cart import Cart

from .models import Order, OrderItem
from .forms import OrderCreateForm
from .tasks import order_created


def order_create(request):
    cart = Cart(request)

    if request.method == "POST":
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = Order()

            shipping_address, _ = ShippingAddress.objects.get_or_create(
                street=form.cleaned_data["street"],
                apartment=form.cleaned_data["apartment"],
                city=form.cleaned_data["city"],
                postal_code=form.cleaned_data["postal_code"],
                state=form.cleaned_data["state"],
                country=form.cleaned_data["country"],
            )

            order = Order(
                first_name=form.cleaned_data["first_name"],
                last_name=form.cleaned_data["last_name"],
                email=form.cleaned_data["email"],
                shipping_address=shipping_address,
            )

            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount

            order.save()

            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    book=item["book"],
                    price=item["price"],
                    quantity=item["quantity"],
                )

            cart.clear()
            order_created.delay(order.id)  # Asynchronous task
            request.session["order_id"] = order.id
            return redirect(reverse("payment:process"))

    else:
        if request.user.is_authenticated:
            initial_data = {
                "first_name": request.user.first_name,
                "last_name": request.user.last_name,
                "email": request.user.email,
            }

            shippingaddress = ShippingAddress.objects.filter(
                user=request.user, main=True
            ).first()
            if shippingaddress:
                initial_data["street"] = shippingaddress.street
                initial_data["apartment"] = shippingaddress.apartment
                initial_data["city"] = shippingaddress.city
                initial_data["postal_code"] = shippingaddress.postal_code
                initial_data["state"] = shippingaddress.state
                initial_data["country"] = shippingaddress.country

            form = OrderCreateForm(initial=initial_data)

        else:
            form = OrderCreateForm()

    return render(request, "orders/order/create.html", {"cart": cart, "form": form})


@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "orders/order/detail.html", {"order": order})


@login_required
def order_cancel(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.order_status = "canceled"
    order.save()
    return redirect("user:dashboard")


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "admin/orders/order/detail.html", {"order": order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string("orders/order/pdf.html", {"order": order})
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f"filename=order_{order.id}.pdf"
    weasyprint.HTML(string=html).write_pdf(
        response, stylesheet=[weasyprint.CSS(settings.STATIC_ROOT / "css/pdf.css")]
    )
    return response

bookstore/orders/templates/orders/order/create.html
{% extends "base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}

<h3>Checkout</h3>
<table class="tables">
    <thead>
        <tr>
            <th>Photo</th>
            <th>Title</th>
            <th>Author</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with book=item.book %}
        <tr>
            <td>
                <img class="bookimagesmall" src="{{ book.img_url }}" alt="Book image">
            </td>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>{{ item.quantity }}</td>
            <td>${{ item.price }}</td>
            <td>${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
        <tr>
            <td>Subtotal</td>
            <td colspan="4"></td>
            <td>${{ cart.calc_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>
                Coupon "{{ cart.coupon.code }}"
                ({{ cart.coupon.discount }}% discount)
            </td>
            <td colspan="4"></td>
            <td>
                - ${{ cart.get_discount|floatformat:2 }}
            </td>
        </tr>
        {% endif %}
        <tr>
            <td><b>Total</b></td>
            <td colspan="4"></td>
            <td>$<b>{{ cart.get_total_price_after_discount|floatformat:2 }}</b></td>
        </tr>
    </tbody>
</table>
<br>
<div class="order-info">
    <h4>Order</h4>
    <ul style="text-align:center; list-style: none;">
        {% for item in cart %}
        <li>
            {{ item.quantity }}x <b>{{ item.book.title }} by {{ item.book.author }}</b>
            <span>${{ item.total_price }}</span>
        </li>
        {% endfor %}
   
    {% if cart.coupon %}
        <li>
            Coupon "{{ cart.coupon.code }}"
            ({{ cart.coupon.discount }}% discount)
            <span> -$<b>{{ cart.get_discount|floatformat:2 }}</b></span>
        </li>
    {% endif %}
</ul>
    <p>Total: $<b>{{ cart.get_total_price_after_discount|floatformat:2 }}</b></p>
</div>

<div id="review-form" class="form--group">
<form class="form--review" method="post">
    <div class="form--control">
    {{ form.as_p }}
    </div>
    <p><input type="submit" class="btn btn-primary" value="Submit order"></p>
    {% csrf_token %}
</form>
</div>

{% endblock %}

bookstore/orders/templates/orders/order/created.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<h3>Thank you for the order</h3>
<p>Your order no <strong>{{ order.id }}</strong> has been created successfully. Details were sent to the e-mail
    provided.</p>
<p>You can view your orders in your <a href="{% url 'user:dashboard' %}">profile</a>.</p>
{% endblock %}

bookstore/orders/templates/orders/order/detail.html
{% extends "base.html" %}

{% block title %}Order no {{ order.id }} {% endblock %}

{% block content %}

<div>
    <h3>Order no {{ order.id }} </h3>
    <ul class="order-list">
        <li>
            <a href="#" onclick="window.print();">
                Print order
            </a>
        </li>
    </ul>
    <table class="tables">
        <tr>
            <th>Created</th>
            <td>{{ order.created }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ order.first_name }} {{ order.last_name }}</td>
        </tr>
        <tr>
            <th>E-mail</th>
            <td><a href="mailto: {{ order.email }}">{{ order.email }}</a></td>
        </tr>
        <tr>
            <th>Address</th>
            <td>
                {{ order.shipping_address.street }} {{ order.shipping_address.apartment }},
                {{ order.shipping_address.postal_code }} {{ order.shipping_address.city }},
                {{ order.shipping_address.state }} {{ order.shipping_address.country }}
            </td>
        </tr>
        <tr>
            <th>Total</th>
            <td>${{ order.get_total_cost|stringformat:".2f" }}</td>
        </tr>
        <tr>
            <th>Payment Status</th>
            <td> {% if order.order_status == 'canceled' and order.paid %}
                refund initiated
                {% endif %}
                {% if order.order_status != 'canceled' and order.paid %} paid {% endif %}
                {% if order.order_status == 'canceled' and order.paid == False %}
                canceled
                {% endif %}  
                {% if order.order_status != 'canceled' and order.paid == False %}    
                <form action="{% url 'payment:laterprocess' %}" method="post">
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <button class="pay_now" type="submit"><i class="fa-regular fa-credit-card"> pay</i></button>
                    {% csrf_token %}
                </form>
                {% endif %}
                </td>
        </tr>
        <tr>
            <th>Order Status</th>
            <td>{{ order.order_status }}</td>            
        </tr>
    </table>
</div>
<br>

{% if order.order_status == 'canceled' %}
<p>Order has been canceled.</p>
{% else %}
<div class="cancel-order-form">
    <form action="{% url 'orders:order_cancel' order.id  %}" method="post">
        <input type="hidden" name="order_id" value="{{ order.id }}">
        <button class="btn btn-danger" type="submit">Cancel order</button>
        {% csrf_token %}
    </form>
</div>
{% endif %}

<br>
<div>
    <h3>Ordered books</h3>
    <table class="tables">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th colspan="1"></th>
                <th>Amount</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
            <tr>
                <td>{{ item.book.title }}</td>
                <td>{{ item.book.author }}</td>
                <td colspan="1"></td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.price|stringformat:".2f" }}</td>
                <td>${{ item.get_cost|stringformat:".2f" }}</td>
            </tr>
            {% endfor %}
            
            {% if order.coupon %}
            <tr>
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td>${{ order.get_total_cost_before_discount|floatformat:2 }}</td>
            </tr>
            <tr>
                <td>
                    Coupon "{{ order.coupon.code }}"
                    ({{ order.coupon.discount }}% discount)
                </td>
                <td colspan="4"></td>
                <td>
                    - ${{ order.get_discount|floatformat:2 }}
                </td>
            </tr>
            {% endif %}
            <tr>
                <td><b>Total</b></td>
                <td colspan="4"></td>
                <td>${{ order.get_total_cost|stringformat:".2f" }}</td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

bookstore/orders/templates/orders/order/pdf.html
<html>
    <body>
        <h3>Bookstore</h3>
        <p>
            Invoice no {{ order.id }}
            <br>
            <span>
                {{ order.created|date:"M d, Y" }}
            </span>
        </p>
        <h4>Buyer</h4>
        <p>
            {{ order.first_name }} {{ order.last_name }}
            <br>
            {{ order.email }}
            <br>
            {{ order.shipping_address.street }} {{ order.shipping_address.apartment }},
            <br>
            {{ order.shipping_address.postal_code }} {{ order.shipping_address.city }},
            <br>
            {{ order.shipping_address.state }} {{ order.shipping_address.country }}
        </p>
        <h4>Order</h4>
        <table class="tables">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Amount</th>
                    <th>Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with book=item.book %}
                <tr>
                    <td>
                        <img class="bookimagesmall" src="{{ book.img_url }}" alt="Book image">
                    </td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>${{ item.price }}</td>
                    <td>${{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr>
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td>$<b>{{ cart.calc_total_price }}</b></td>
                </tr>
            </tbody>
        </table>
        <h4>Status</h4>
        <p>{% if order.paid %}Paid{% else %}Waiting for payment{% endif %}</p>        
    </body>
</html>