bookstore/book/urls.py
from django.urls import path

from . import views
from .feed import LatestArrivals

app_name = "book"

urlpatterns = [
    path("", views.book_list, name="book_list"),
    path("book/<str:slug>/", views.book_detail, name="book_detail"),
    path("<int:bookid>/review/", views.post_review, name="post_review"),
    path("tag/<slug:tag_slug>/", views.book_list, name="book_list_by_tag"),
    path("search/", views.book_search, name="book_search"),
    path("category/<int:catid>/", views.category_display, name="category_display"),
    path("category/all/", views.category_display, name="all_categories"),
    path("edit_review/<int:review_id>/", views.edit_review, name="edit_review"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("feed/", LatestArrivals(), name="book_feed"),
    path("like/", views.review_like, name="like"),
]

bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("filter/", include("filter.urls", namespace="filter")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("author/", include("author.urls", namespace="author")),
    path("", include("book.urls", namespace="book")),
    path("", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/payment/urls.py
from django.urls import path

from . import views
from . import webhooks

app_name = "payment"

urlpatterns = [
    path("process/", views.payment_process, name="process"),
    path("laterprocess/", views.later_payment_process, name="laterprocess"),
    path("completed/", views.payment_completed, name="completed"),
    path("canceled/", views.payment_canceled, name="canceled"),
    path("webhook/", webhooks.stripe_webhook, name="stripe-webhook"),
]

bookstore/payment/views.py
from decimal import Decimal

from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
from orders.models import Order

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }

        for item in order.items.all():
            session_data["line_items"].append(
                {
                    "price_data": {
                        "unit_amount": int(item.price * Decimal("100")),
                        "currency": "usd",
                        "product_data": {
                            "name": item.book.title,
                        },
                    },
                    "quantity": item.quantity,
                }
            )

        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code, percent_off=order.discount, duration="once"
            )
            session_data["discounts"] = [{"coupon": stripe_coupon.id}]

        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    return render(request, "payment/process.html", locals())


def payment_completed(request):
    return render(request, "payment/completed.html")


def payment_canceled(request):
    return render(request, "payment/canceled.html")


def later_payment_process(request):
    order_id = request.POST.get("order_id")
    order = get_object_or_404(Order, id=order_id)

    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }

        for item in order.items.all():
            session_data["line_items"].append(
                {
                    "price_data": {
                        "unit_amount": int(item.price * Decimal("100")),
                        "currency": "usd",
                        "product_data": {
                            "name": item.book.title,
                        },
                    },
                    "quantity": item.quantity,
                }
            )

        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code, percent_off=order.discount, duration="once"
            )
            session_data["discounts"] = [{"coupon": stripe_coupon.id}]

        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)

    return render(request, "payment/process.html", locals())

bookstore/payment/templates/payment/canceled.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment cancelled{% endblock %}

{% block content %}

<h3>Payment cancelled</h3>
<p>Your payment has not been proceed.</p>

{% endblock %}

bookstore/payment/templates/payment/completed.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment succeeded{% endblock %}

{% block content %}

<h3>Payment succeeded</h3>
<p>Your payment has been proceed successfully.</p>

{% endblock %}

bookstore/payment/templates/payment/process.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment{% endblock %}

{% block content %}

<h3>Order summary</h3>
<table class="tables">
    <thead>
        <tr>
            <th>Photo</th>
            <th>Title</th>
            <th>Author</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr>
            <td>
                <img class="bookimagesmall" src="{{ item.book.img_url }}" alt="Book image">
            </td>
            <td>{{ item.book.title }}</td>
            <td>{{ item.book.author }}</td>
            <td>{{ item.quantity }}</td>
            <td>${{ item.price }}</td>
            <td>${{ item.get_cost }}</td>
        </tr>
        {% endfor %}
        {% if order.coupon %}
        <tr>
            <td>Subtotal</td>
            <td colspan="4"></td>
            <td>${{ order.get_total_cost_before_discount|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>
                Coupon "{{ order.coupon.code }}"
                ({{ order.discount }}% discount)
            </td>
            <td colspan="4"></td>
            <td>
                - ${{ order.get_discount|floatformat:2 }}
            </td>
        </tr>
        {% endif %}
        <tr>
            <td><b>Total</b></td>
            <td colspan="4"></td>
            <td>$<b>{{ order.get_total_cost|floatformat:2 }}</b></td>
        </tr>
    </tbody>
</table>

<div id="review-form" class="form--group">
<form class="form--review" action="{% url 'payment:process' %}" method="post">
    <p><input type="submit" class="btn btn-primary" value="Pay"></p>
    {% csrf_token %}
</form>
</div>

{% endblock %}