bookstore/author/urls.py
from django.urls import path

from . import views

app_name = "author"

urlpatterns = [
    path("", views.author_list, name="author_list"),
    path("author/<str:slug>/", views.author_detail, name="author_detail"),
]

bookstore/book/urls.py
from django.urls import path

from . import views
from .feed import LatestArrivals

app_name = "book"

urlpatterns = [
    path("", views.book_list, name="book_list"),
    path("book/<str:slug>/", views.book_detail, name="book_detail"),
    path("<int:bookid>/review/", views.post_review, name="post_review"),
    path("tag/<slug:tag_slug>/", views.book_list, name="book_list_by_tag"),
    path("search/", views.book_search, name="book_search"),
    path("category/<int:catid>/", views.category_display, name="category_display"),
    path("category/all/", views.category_display, name="all_categories"),
    path("edit_review/<int:review_id>/", views.edit_review, name="edit_review"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("feed/", LatestArrivals(), name="book_feed"),
    path("like/", views.review_like, name="like"),
]

bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("filter/", include("filter.urls", namespace="filter")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("author/", include("author.urls", namespace="author")),
    path("", include("book.urls", namespace="book")),
    path("", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:book_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:book_id>/", views.cart_remove, name="cart_remove"),
    path("toggle/<int:book_id>/", views.cart_toggle, name="cart_toggle"),
]

bookstore/book/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from taggit.managers import TaggableManager

from author.models import Author


class Category(models.Model):
    catid = models.AutoField(primary_key=True)
    cat_name = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["cat_name"]
        indexes = [models.Index(fields=["cat_name"])]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return f"{self.cat_name}"

    def get_absolute_url(self):
        return reverse("book:category_display", args=[self.catid])


class Book(models.Model):
    bookid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=250, blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    img_url = models.URLField()
    available = models.BooleanField(default=True)
    slug = models.SlugField(default="", null=False)
    created = models.DateTimeField(auto_now_add=True)
    catid = models.ForeignKey(Category, on_delete=models.CASCADE)
    authorid = models.ForeignKey(
        Author, related_name="author", on_delete=models.SET_NULL, null=True, blank=True
    )
    tags = TaggableManager()

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["bookid", "slug"]),
            models.Index(fields=["title"]),
            models.Index(fields=["author"]),
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return f"{self.title} by {self.author}"

    def get_absolute_url(self):
        return reverse("book:book_detail", args=[self.slug])


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="review")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(
        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
    )
    body = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    user_liked = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="review_like", blank=True
    )

    class Meta:
        ordering = ["-created"]
        unique_together = ["book", "user"]
        indexes = [models.Index(fields=["book"]), models.Index(fields=["user"])]

    def __str__(self):
        return f"Review added by {self.user.username} for book {self.book}"

bookstore/book/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("rating", "body")


class SearchForm(forms.Form):
    query = forms.CharField()

bookstore/book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Avg
from django.contrib.postgres.search import TrigramSimilarity
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseBadRequest

from taggit.models import Tag

from cart.forms import CartAddBookForm
from .recommender import Recommender
from .models import Book, Category, Review
from .forms import ReviewForm, SearchForm


def book_list(request, tag_slug=None):
    book_list = Book.objects.all()
    tag = None
    cart_book_form = CartAddBookForm()

    books_per_page = request.GET.get("books_per_page", 12)
    if int(books_per_page) <= 0:
        return HttpResponseBadRequest("Invalid number of books per page")
    books_per_page = int(books_per_page)

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        book_list = book_list.filter(tags__in=[tag])

    paginator = Paginator(book_list, books_per_page)
    page_number = request.GET.get("page", 1)
    try:
        books = paginator.page(page_number)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    return render(
        request,
        "book/list.html",
        {
            "books": books,
            "tag": tag,
            "cart_book_form": cart_book_form,
            "books_per_page": books_per_page,
        },
    )


def book_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    cart_book_form = CartAddBookForm()

    r = Recommender()
    recommended_books = r.suggest_books_for([book], 4)

    reviews = book.review.filter(active=True)
    form = ReviewForm(initial={"user": request.user.username})

    avg_rating = reviews.aggregate(avg_rating=Avg("rating"))["avg_rating"]

    book_tags_ids = book.tags.values_list("id", flat=True)
    similar_books = Book.objects.filter(tags__in=book_tags_ids).exclude(
        bookid=book.bookid
    )
    similar_books = similar_books.annotate(same_tags=Count("tags")).order_by(
        "-same_tags"
    )[:3]

    user_left_review = False
    if request.user.is_authenticated:
        user_left_review = Review.objects.filter(book=book, user=request.user).exists()

    return render(
        request,
        "book/detail.html",
        {
            "book": book,
            "reviews": reviews,
            "form": form,
            "similar_books": similar_books,
            "cart_book_form": cart_book_form,
            "avg_rating": avg_rating,
            "user_left_review": user_left_review,
            "recommended_books": recommended_books,
        },
    )


@login_required
@require_POST
def post_review(request, bookid):
    book = get_object_or_404(Book, bookid=bookid)

    if request.user.is_authenticated:
        form = ReviewForm(data=request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.book = book
            review.user = request.user
            review.save()
            return redirect(review.book.get_absolute_url())
    else:
        form = ReviewForm(data=request.POST)

    return render(request, "book/review.html", {"book": book, "form": form})


@login_required
def edit_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)

    if request.user != review.user:
        return HttpResponseForbidden("You don't have permission to edit this review.")

    if request.method == "POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect(review.book.get_absolute_url())

    else:
        form = ReviewForm(instance=review)

    return render(
        request,
        "book/edit_review.html",
        {
            "form": form,
            "review": review,
        },
    )


@login_required
@require_POST
def review_like(request):
    review_id = request.POST.get("id")
    action = request.POST.get("action")
    if review_id and action:
        try:
            review = Review.objects.get(id=review_id)
            if action == "like":
                review.user_liked.add(request.user)
            else:
                review.user_liked.remove(request.user)
            return JsonResponse({"status": "ok"})
        except Review.DoesNotExist:
            pass
    return JsonResponse({"status": "error"})


def book_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = (
                Book.objects.annotate(
                    similarity=TrigramSimilarity("title", query),
                )
                .filter(similarity__gt=0.1)
                .order_by("-similarity")
            )

    return render(
        request, "book/search.html", {"form": form, "query": query, "results": results}
    )


def category_display(request, catid=None):
    if catid is None:
        book_list = Book.objects.all()
        category = "All"
    else:
        category = get_object_or_404(Category, pk=catid)
        book_list = Book.objects.filter(catid=catid)

    cart_book_form = CartAddBookForm()

    books_per_page = request.GET.get("books_per_page", 12)
    if int(books_per_page) <= 0:
        return HttpResponseBadRequest("Invalid number of books per page")
    books_per_page = int(books_per_page)

    paginator = Paginator(book_list, books_per_page)
    page_number = request.GET.get("page", 1)
    try:
        books = paginator.page(page_number)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    return render(
        request,
        "category/detail.html",
        {
            "category": category,
            "books": books,
            "cart_book_form": cart_book_form,
            "books_per_page": books_per_page,
        },
    )


def about(request):
    return render(request, "other/about.html")


def contact(request):
    return render(request, "other/contact.html")

bookstore/book/templates/book/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ book.title }} by {{ book.author }}{% endblock %}

{% block content %}
<h1> {{ book.title }} by {{ book.author }} </h1>

<div class="book-details">
    <div class="book-image">
        <img class="bookimage" src="{{ book.img_url }}" alt="Book image">
    </div>
    <div class="book-info">
        <b>Title:</b> {{ book.title }}
        <br>
        <b>Author:</b> <a href="{% url 'author:author_detail' book.authorid.slug %}">{{ book.author }}</a>
        <div class="book-rating">
            <b>Average rating:</b> 
            {% if not avg_rating %}
            N/A
            {% else %}
            {{ avg_rating|floatformat:2 }}
            {% endif %}
        </div>
        <div class="book-price">
            <b>Price:</b> &#36;{{ book.price }}
        </div>
        <form id="addtocart" action="{% url 'cart:cart_add' book.bookid %}" method="post">
            {{ cart_book_form }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Add to cart">
        </form>
    </div>
    <div class="book-description">
        <b>Description:</b>
        <p id="book-description">
            {{ book.description | linebreaks }}
        </p>
    </div>
</div>



<h4>Might interest you as well:</h4>
<div class="bookcontainer">

    {% for book in similar_books %}
    <div class="book">
        <div class="bookdetails">
            <a href="{{ book.get_absolute_url }}">
                <img class="bookimage" src="{{ book.img_url }}" alt="Book image">
                {{ book.title }}
            </a>
            <br>
            {{ book.author }}
            <br>
            &#36;{{ book.price }}
            <form id="addtocart" action="{% url 'cart:cart_add' book.bookid %}" method="post">
                {{ cart_book_form }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Add to cart">
            </form>
        </div>
    </div>

    {% empty %}
    <p>Nothing here yet.</p>
    {% endfor %}
</div>


{% if recommended_books %}
<h4>Customers who purchased this item also bought:</h4>
<div class="bookcontainer">
{% for book in recommended_books %}
<div class="book">
    <div class="bookdetails">
        <a href="{{ book.get_absolute_url }}">
            <img class="bookimage" src="{{ book.img_url }}" alt="Book image">
            {{ book.title }}
        </a>
        <br>
        {{ book.author }}
        <br>
        &#36;{{ book.price }}
        <form id="addtocart" action="{% url 'cart:cart_add' book.bookid %}" method="post">
            {{ cart_book_form }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Add to cart">
        </form>
    </div>
</div>
{% endfor %}
</div>
{% endif %}


{% with reviews.count as total_reviews %}
<h2 style="text-align: center;">
    {% if total_reviews == 1 %}
    {{ total_reviews }} review
    {% else %}
    {{ total_reviews }} reviews
    {% endif %}
</h2>
{% endwith %}

{% comment %} {% include "review/filter.html" %} {% endcomment %}
<br>
{% for review in reviews reversed %}
<div style="text-align: center;" class="review">
    <p class="info">
        <b>Review {{ forloop.counter }} added by {{ review.user }} on
            {{ review.created }}</b>
        <br>
        {{ review.name }} <b>rated:</b> {{ review.rating }}/5
        {% if user.is_authenticated and review.user == user %}
        <a href="{% url 'book:edit_review' review.id %}?next={{ request.path|urlencode }}" class="btn btn-info">Edit</a>
        {% endif %}
    </p>

    {% if not review.body %}
    <p><i>User did not leave any review.</i></p>
    {% else %}
    {{ review.body|linebreaks }}
    {% endif %}
    {% with total_likes=review.user_liked.count user_liked=review.user_liked.all %}
    <div class="count">
        <div class="total-likes"><span>{{ total_likes }} Agree</span>
        <a 
            href="javascript:void(0);" 
            class="agree button"
            data-id="{{ review.id }}" 
            data-action="{% if request.user in user_liked %}un{% endif %}like" 
            data-url="{% url 'book:like' %}"
        >
            {% if request.user not in user_liked %}
            [+1 Agree]
            {% else %}
            [-1 Disagree]
            {% endif %}
        </a>
        </div>
    </div>
    {% endwith %}
</div>
{% empty %}
<p>There are no reviews yet.</p>
{% endfor %}
<br>

{% if user.is_authenticated %}
{% if user_left_review %}
<p>You have already left a review for this book.</p>
{% else %}
{% include "book/includes/review_form.html" %}
{% endif %}
{% else %}
<p><a href="/user/login">Login</a> or <a href="/user/register">Register</a> to rate a book or post a review.</p>
{% endif %}

<script src="{% static 'js/agreeButton.js' %}" defer></script>

{% endblock %}

bookstore/book/templates/book/edit_review.html
{% extends "base.html" %}

{% block title %}Edit review{% endblock %}

{% block content %}

<h2 style="text-align: center;">Edit review</h2>
<div id="review-form" class="form--group">
    <form class="form--review" action="{% url 'book:edit_review' review.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }}
        <div class="form--control">
            {{ field }}
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Edit review">
    </form>
</div>

{% endblock %}

bookstore/book/templates/book/latest_books.html
<div class="bookcontainer">
{% for book in latest_books %}

<div class="bookdetails">
    <a href="{{ book.get_absolute_url }}">
        <img class="bookimage" src="{{ book.img_url }}" alt="Book image">
        {{ book.title }}
    </a>
    {{ book.author }}
    <br>
    &#36;{{ book.price }}
</div>
{% endfor %}
</div>

bookstore/book/templates/book/list.html
{% extends "base.html" %}
{% load book_tags %}
{% load static %}

{% block title %}Bookstore{% endblock %}

{% block content %}

<h1> Bookstore </h1>

{% if tag %}
<h4>Books with tag: "{{ tag.name }}"</h4>
{% endif %}
<form method="get" action="{% url 'book:book_list' %}" id="booksPerPageForm">
    <label for="booksPerPage">Books per page:</label>
    <select name="books_per_page" id="itemsPerPage" onchange="this.form.submit()">
        <option value="6" {% if books_per_page == 6 %}selected{% endif %}>6</option> 
        <option value="12" {% if books_per_page == 12 %}selected{% endif %}>12</option>
        <option value="18" {% if books_per_page == 18 %}selected{% endif %}>18</option>
    </select>
</form>
<div class="bookcontainer">

    {% for book in books %}

    <div class="book">
        <div class="bookdetails">

            <div class="icon-container">
                <a id="wishlist-icon" class="wishlist-icon" data-bookid="{{ book.bookid }}" data-csrf="{{ csrf_token }}" href="javascript:void(0)" data-bookid="{{ book.bookid }}">
                    <i class="fa-regular fa-heart"></i>
                    <!-- <i class="fa-solid fa-heart"></i> For added -->
                </a>
                <a id="cart-icon" class="cart-icon" href="javascript:void(0)" data-bookid="{{ book.bookid }}">
                    <i class="fa-solid {% if book_in_cart %}fa-check{% else %}fa-basket-shopping{% endif %}"></i>
                </a>
            </div>

            <a class="booklink" href="{% url 'book:book_detail' book.slug %}">
                <img class="bookimage" src="{{ book.img_url }}" alt="Book image">

                {{ book.title|truncatechars:30 }}
            </a>
            <br>
            <a href="{% url 'author:author_detail' book.authorid.slug %}">{{ book.author|truncatechars:30 }}</a>          
            <br>
            &#36;{{ book.price }}
            <p class="tags">Tags:
                {% spaceless %}
                {% for tag in book.tags.all %}

                <a href="{% url 'book:book_list_by_tag' tag.slug %}">{{ tag.name.strip }}</a>{% if not forloop.last %},
                {% endif %}

                {% endfor %}
                {% endspaceless %}
            </p>
            <form id="addtocart" action="{% url 'cart:cart_add' book.bookid %}" method="post">
                {{ cart_book_form }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Add to cart">
            </form>
        </div>
    </div>

    {% endfor %}
</div>
{% include "pagination.html" with page=books %}

<h4>Latest arrivals:</h4>
{% show_latest_books 6 %}
<br>
<p>We have {% total_books %} books in our store.</p>

<script>
    const csrfToken = "{{ csrf_token }}";
</script>

{% endblock %}

bookstore/book/templates/book/review.html
{% extends "base.html" %}

{% block title %}Add review{% endblock %}

{% block content %}
    {% if review %}
        <h3>Your review has been added.</h3>
        <p><a href="{{ book.get_absolute_url }}">Back to book</a></p>
    {% else %}
        {% include "book/includes/review_form.html" %}
    {% endif %}
{% endblock %}

bookstore/book/templates/book/search.html
{% extends "base.html" %}
{% load book_tags %}

{% block title %}Search{% endblock %}

{% block content %}

<h1> Bookstore </h1>
{% comment %} 
{% include "book/filter.html" %} {% endcomment %}
<br>
{% if query %}

<h4>Search results of "{{ query }}"</h4>
<h5 style="text-align: center;">
    {% with results.count as total_results %}

    {% if total_results == 1 %}
    Found {{ total_results }} item.
    {% else %}
    Found {{ total_results }} items.
    {% endif %}

    {% endwith %}
</h5>
<div class="bookcontainer">
    {% for book in results %}
    <div class="book">
        <div class="bookdetails">
            <a href="{{ book.get_absolute_url }}">
                <img class="bookimage" src="{{ book.img_url }}" alt="Book image">
                {{ book.title }}
            </a>
            <br>
            {{ book.author }}
            <br>
            &#36;{{ book.price }}
        </div>
    </div>
    {% endfor %}
</div>

<p><a href="{% url 'book:book_search' %}">Search again</a></p>

{% else %}

<h4>Search for books by title</h4>
<div id="review-form" class="form--group">
<form class="form--review" method="get">
    <div class="form--control">
        {{ form.as_p }}
    </div>
   <p><input type="submit" class="btn btn-primary" value="Search"></p>
</form>
</div>

{% endif %}

{% endblock %}