bookstore/author/urls.py
from django.urls import path

from . import views

app_name = "author"

urlpatterns = [
    path("", views.author_list, name="author_list"),
    path("author/<str:slug>/", views.author_detail, name="author_detail"),
]

bookstore/book/urls.py
from django.urls import path

from . import views
from .feed import LatestArrivals

app_name = "book"

urlpatterns = [
    path("", views.book_list, name="book_list"),
    path("book/<str:slug>/", views.book_detail, name="book_detail"),
    path("<int:bookid>/review/", views.post_review, name="post_review"),
    path("tag/<slug:tag_slug>/", views.book_list, name="book_list_by_tag"),
    path("search/", views.book_search, name="book_search"),
    path("category/<int:catid>/", views.category_display, name="category_display"),
    path("category/all/", views.category_display, name="all_categories"),
    path("edit_review/<int:review_id>/", views.edit_review, name="edit_review"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("feed/", LatestArrivals(), name="book_feed"),
    path("like/", views.review_like, name="like"),
]

bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("filter/", include("filter.urls", namespace="filter")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("author/", include("author.urls", namespace="author")),
    path("", include("book.urls", namespace="book")),
    path("", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/author/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=250)
    surname = models.CharField(max_length=250)
    bio = models.TextField(blank=True)
    photo = models.ImageField(
        upload_to="author_photos/%Y/%m/%d/", null=True, blank=True
    )
    own_url_page = models.URLField()
    email = models.EmailField(blank=True)
    birthdate = models.DateField(null=True, blank=True)

    slug = models.SlugField(default="", null=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["surname"]
        indexes = [
            models.Index(fields=["slug"]),
            models.Index(fields=["name", "surname"]),
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"{self.name} {self.surname}"

    def get_absolute_url(self):
        return reverse("author:author_detail", args=[self.slug])

bookstore/author/views.py
from django.shortcuts import render, get_object_or_404

from book.models import Book
from .models import Author


def author_list(request):
    all_authors = Author.objects.all()
    return render(request, "list.html", {"all_authors": all_authors})


def author_detail(request, slug):
    author = get_object_or_404(Author, slug=slug)
    books = Book.objects.filter(author=author)
    return render(request, "detail.html", {"author": author, "books": books})

bookstore/author/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}

<h1> {{ author.name }} {{ author.surname }} </h1>

{% if author.photo %}
<p><img src="{{ author.photo.url }}" alt="Author Photo" width="250"></p>
{% else %}
    <p><img src="{% static 'img/no-photos.png' %}" alt="No Photo" width="150"></p>
    <p style="font-size:12px;"><small>Photo credits: 
        <a href="https://www.flaticon.com/free-icons/no-photo" title="no photo icons">No photo icons created by Those Icons - Flaticon</a>
    </small>
    </p>
{% endif %}
<p>Author's page: <a href="{{ author.own_url_page }}" target="_blank">{{ author.own_url_page }}</a></p>
<p>Date of birth: {{ author.birthdate }}</p>
<p>{{ author.bio }}</p>
<br>
<br>
<h3>Books by this author</h3>
<div class="bookcontainer">
    {% for book in books %}
    
    <div class="book">
        <div class="bookdetails">
            <a class="booklink" href="{% url 'book:book_detail' book.slug %}">
                <img class="bookimage" src="{{ book.img_url }}" alt="Book image">

                {{ book.title|truncatechars:30 }}
            </a>
            <br>
            {{ book.author|truncatechars:30 }}
            <br>
            &#36;{{ book.price }}
        
        </div>
    </div>

    {% empty %}
    <p class="author-books-info"> Currently there are no books by this author in our store. </p>
    {% endfor %}
</div>
{% endblock %}

bookstore/author/templates/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Bookstore{% endblock %}

{% block content %}

<h1> Authors </h1>
<div class="authors">
    {% for author in all_authors %}
    <div class="author-box">
        <a class="author-link" href="{% url 'author:author_detail' author.slug %}">
            {% if author.photo %}
            <img class="author-photo" src="{{ author.photo.url }}" alt="Author Photo">
            {% else %}
            <img class="author-photo" src="{% static 'img/no-photos.png' %}" alt="No Photo">
            {% endif %}
        <p class="author-link">{{ author.name }} {{ author.surname }}</p></a>
    </div>
    {% endfor %}
</div>
{% endblock %}